export const unwantedKeywords = new Set<string>([
  'linkedin','tech','bank','verify','hello','team','discuss',
  'unsubscribe', 'newsletter', 'marketing', 'advertisement', 'promo', 'sale',
  'discount', 'offer', 'deal', 'limited time', 'exclusive', 'free trial',
  'subscription', 'automated', 'noreply', 'no-reply', 'donotreply', 'do-not-reply',
  'bulk', 'mass', 'broadcast', 'announcement', 'alert', 'notification',
  'update', 'digest', 'weekly', 'daily', 'monthly', 'quarterly',
  'survey', 'feedback', 'rating', 'review', 'opinion',
  'verification', 'confirm', 'activate', 'validate',
  'account', 'password', 'security', 'login', 'access',
  'invoice', 'receipt', 'bill', 'statement', 'transaction',
  'shipping', 'delivery', 'tracking', 'order',
  'support', 'help', 'assistance', 'inquiry','jobs',
  'job', 'career', 'recruitment', 'hiring', 'vacancy',
  'social', 'network', 'connect', 'friend', 'follow',
  'invitation', 'invite', 'join', 'welcome',
  'webinar', 'seminar', 'event', 'conference',
  'ecommerce', 'shop', 'store', 'buy', 'purchase',
  'campaign', 'fundraising', 'donation', 'charity',
  'report', 'analytics', 'statistics', 'metrics',
  'auto', 'bot', 'robot', 'automated', 'system',
  'info', 'contact', 'admin', 'postmaster', 'mailer',
  'account', 'job', 'jobs', 'bots', 'invitation', 'notifications', 'no-reply','jobalerts','mailer','alert',
  'noreply', 'mailer', 'alert', 'updates', 'newsletter', 'support', 'info', 
  'contact', 'admin', 'automated', 'automatic', 'robot', 'reminder', 'subscribe',
  'unsubscribe', 'promotion', 'offers', 'deal', 'campaign', 'transaction', 
  'receipt', 'invoice', 'confirmation', 'welcome', 'survey', 'feedback', 'terms',
  'policy', 'announcement', 'message', 'system', 'notification', 'broadcast',
  'service', 'platform', 'ecommerce', 'subscription', 'delivery', 'shipment',
  'security', 'verification', 'activation', 'billing', 'update', 'thank you',
  'thanks', 'request', 'response', 'information', 'order', 'auto', 'thankyou',
  'congratulations', 'winners', 'winner', 'prize', 'cash', 'gift', 'gift card',
  'savings', 'voucher', 'free', 'discount', 'coupon', 'buy now', 'order now',
  'call now', 'limited time', 'exclusive deal', 'urgent', 'risk-free', 'act now',
  'apply now', 'save big', 'special promotion', 'guaranteed', 'no cost', 'limited offer',
  'earn money', 'extra income', 'work from home', 'make money', 'click here', 'winner',
  'claim prize', 'win big', 'free access', 'free trial', 'free quote', 'free info',
  'cheap', 'lowest price', 'best price', 'bargain', 'discounted', 'lowest rates',
  'low rates', 'high income', 'financial freedom', 'financial success', 'secret',
  'hidden charges', 'affordable', 'compare rates', 'debt relief', 'debt consolidation',
  'get paid', 'extra cash', 'fast cash', 'quick cash', 'make money online',
  'online biz opportunity', 'biz op', 'home based business', 'make money fast',
  'multilevel marketing', 'mlm', 'referral bonus', 'network marketing', 'work from home job',
  'income', 'promotion', 'online business', 'work at home', 'earn cash', 'be your own boss',
  'free membership', 'risk-free trial', 'limited access', 'personal loan', 'cash bonus',
  'credit card debt', 'credit repair', 'loan', 'consolidate debt', 'fast money',
  'guaranteed approval', 'fast cash', 'no fees', 'bad credit', 'easy money', 'instant cash',
  'unsecured credit', 'credit card offers', 'investment opportunity', 'investment',
  'trading', 'forex trading', 'binary options', 'funding', 'income opportunity'
].map(word => word.toLowerCase()));


export const unwantedDomains = new Set<string>([

  // Existing domains
  'linkedin.com', 'facebook.com', 'twitter.com', 'instagram.com',
  'mailchimp.com', 'sendgrid.net', 'constantcontact.com', 'salesforce.com',
  'hubspot.com', 'marketo.com', 'mailgun.com', 'amazonses.com',
  'mailjet.com', 'sendpulse.com', 'mailerlite.com', 'aweber.com',
  'getresponse.com', 'campaignmonitor.com', 'convertkit.com',
  'activecampaign.com', 'drip.com', 'klaviyo.com', 'pardot.com',
  'exacttarget.com', 'mailtrack.io', 'yesware.com', 'streak.com',
  'boomeranggmail.com', 'mixmax.com', 'hunter.io', 'zendesk.com',
  'freshdesk.com', 'intercom.io', 'drift.com', 'olark.com',
  'crisp.chat', 'tawk.to', 'livechatinc.com', 'snapengage.com',
  'zopim.com', 'purechat.com', 'smartsupp.com', 'liveperson.com',
  'desk.com', 'helpscout.net', 'groovehq.com', 'kayako.com',
  'uservoice.com', 'surveymonkey.com', 'typeform.com', 'jotform.com',
  'wufoo.com', 'formstack.com', 'cognitoforms.com', 'formsite.com',
  'emailoctopus.com', 'sendinblue.com', 'moosend.com', 'ontraport.com',
  'infusionsoft.com', 'dotdigital.com', 'omnisend.com', 'sendy.co',
  'sendloop.com', 'verticalresponse.com', 'feedblitz.com', 'feedburner.com',

  // Additional domains
  'mailgun.org', 'sendgrid.com', 'mailchimp.net', 'awsapps.com',
  'sparkpost.com', 'postmarkapp.com', 'mandrill.com', 'elasticemail.com',
  'smtp2go.com', 'pepipost.com', 'socketlabs.com', 'smtp.com',
  'rackspace.com', 'zoho.com', 'protonmail.com', 'fastmail.com',
  'godaddy.com', 'bluehost.com', 'hostgator.com', 'dreamhost.com',
  'e.linkedin.com', 'm.facebook.com', 'facebookmail.com', 'twitter.email',
  'instagram.email', 'pinterest.com', 'snapchat.com', 'tiktok.com',
  'reddit.com', 'tumblr.com', 'quora.com', 'medium.com',
  'slack.com', 'asana.com', 'trello.com', 'basecamp.com',
  'github.com', 'gitlab.com', 'bitbucket.org', 'atlassian.com',
  'jira.com', 'confluence.com', 'dropbox.com', 'box.com',
  'evernote.com', 'notion.so', 'airtable.com', 'zapier.com',
  'ifttt.com', 'hootsuite.com', 'buffer.com', 'later.com',
  'sproutsocial.com', 'canva.com', 'adobe.com', 'microsoft.com',
  'office365.com', 'outlook.com', 'hotmail.com', 'live.com',
  'googlemail.com', 'gmail.com', 'yahoo.com', 'aol.com',
  'icloud.com', 'me.com', 'mac.com', 'yandex.com',
  'mail.ru', 'rambler.ru', 'zoho.eu', 'gmx.com',
  'webmail.com', 'hushmail.com', 'tutanota.com', 'mail.com',
  'workday.com', 'adp.com', 'bamboohr.com', 'gusto.com',
  'zenefits.com', 'paychex.com', 'paylocity.com', 'namely.com',
  'quickbooks.com', 'xero.com', 'freshbooks.com', 'wave.com',
  'shopify.com', 'bigcommerce.com', 'woocommerce.com', 'magento.com',
  'squarespace.com', 'wix.com', 'weebly.com', 'wordpress.com',
  'mailerlite.com', 'convertkit.com', 'getresponse.com', 'aweber.com',
  'constantcontact.com', 'activecampaign.com', 'drip.com', 'klaviyo.com',
  'mailjet.com', 'sendpulse.com', 'sendinblue.com', 'moosend.com',
  'ontraport.com', 'infusionsoft.com', 'dotdigital.com', 'omnisend.com',
  'sendy.co', 'sendloop.com', 'verticalresponse.com', 'feedblitz.com',
  'feedburner.com', 'reachmail.com', 'pinpointe.com', 'icontact.com',
  'campaigner.com', 'benchmarkemail.com', 'emma.com', 'bronto.com',
  'sailthru.com', 'listrak.com', 'bluecore.com', 'zaius.com',
  'emarsys.com', 'autopilothq.com', 'customerio.com', 'iterable.com',
  'braze.com', 'leanplum.com', 'appboy.com', 'urbanairship.com',
  'pushwoosh.com', 'onesignal.com', 'airship.com', 'clevertap.com',
  'moengage.com', 'webengage.com', 'vibes.com', 'exponea.com',
  'optimove.com', 'retention.com', 'segment.com', 'amplitude.com',
  'mixpanel.com', 'heap.io', 'kissmetrics.com', 'pendo.io',
  'appcues.com', 'fullstory.com', 'hotjar.com', 'crazyegg.com',
  'luckyorange.com', 'mouseflow.com', 'sessioncam.com', 'clicktale.com',
  'usertesting.com', 'survicate.com', 'qualaroo.com', 'usabilla.com'
]);